### ISSUE TITLE
提案：スクリプトの自動更新

### ISSUE THREAD

**Issue by tanakah** [himuro-majika/futaba_log_search#1]
とても便利なスクリプトで愛用しています！

要望ですが、今の段階だと、スクリプトに更新があったかどうかわざわざサイトを見に行かなければならないので、@updateURLなどで自動更新してくれるようにしていただけるとすごく助かります。

**Comment by himuro-majika** [comment]
ご利用ありがとうございます。

ブラウザとユーザースクリプトマネージャは何をご利用でしょうか？
自動更新ができないのはおそらくWEBからインストールしていない為だと思われます。

このリポジトリはGreasy Forkで公開しているスクリプトとリンクしているので
お手数ですが
一度現在入っているfutaba_log_searchをアンインストールしていただいて、
https://greasyfork.org/ja/scripts/8188-futaba-log-search
からインストールし直していただければ@updateURLがなくてもスクリプトが自動更新できます。
もしくは
Githubからインストールする場合は
ブラウザで[futaba_log_search.user.jsのページ](https://github.com/himuro-majika/futaba_log_search/blob/master/futaba_log_search.user.js)の"Raw"というボタン(もしくは[ここ](https://github.com/himuro-majika/futaba_log_search/raw/master/futaba_log_search.user.js))を開いてインストールしていただければ同じく自動更新できると思います。

Greasy Forkで配布する前提の説明となっていたためわかりにくかったかもしれません。
もし他にご不明な点あればご質問ください。

**Comment by himuro-majika** [comment]
補足です。
今現在スクリプトのメタデータに @version を記載していなかったのでGithubからインストールしてもスクリプトマネージャ側がスクリプトのバージョンが新しくなったかどうか判断できないため自動更新できないかも知れません。
Greasy Forkからインストールした場合は問題ありません。
Greasy Forkでは自動的に @version を追加してくれるため入れていませんでした。
次回リリース時には @version の記載を追加しておきます。
ご指摘ありがとうございました。

**Comment by tanakah** [comment]
環境の説明が後出しになってしまって申し訳ないです。
ブラウザはFirefox42（64bit） 、ユーザースクリプトマネージャはGreaseMonkeyを使用しています。

おそらく、私がGithubからインストールしたのが原因だったのかもしれません（すみません、覚えてないです）。
要望にこたえていただいてありがとうございました。

**Comment by himuro-majika** [comment]
Greasemonkeyであればユーザースクリプトの管理画面でfutaba_log_searchの右クリックメニューで「更新を確認」という項目が有効になっていれば自動更新ができるはずです。

**Comment by tanakah** [comment]
試しに、ひとつ前のバージョン（0.0.1.20151028091150）をGreasy Forkからインストールして、ユーザースクリプトの管理画面でfutaba_log_searchの右クリックメニューから更新の確認をしてみましたが、最新版に更新されませんでした。

**Comment by himuro-majika** [comment]
調べてみましたが、Greasy Forkの履歴から古いバージョンをインストールすると
常に古いバージョンのURLを確認しに行ってしまうようなので
Greasy Forkの履歴からインストールした場合は永久に最新版にならないようです……
普通に最新版をインストールすれば大丈夫なはずです

**Comment by tanakah** [comment]
どうもありがとうございます。
いろいろとお手数掛けて申し訳ないです。スクリプトをインストールする場所やバージョンによっていろいろと条件が変わることは知りませんでした…。Greasy Forkの最新版を改めてインストールし直しました。

これからも無理のない範囲で開発を続けていただければと思います。

**Comment by himuro-majika** [comment]
@versionを追加してスクリプトを更新しました。
プログラムの内容自体は何も変わっていませんが……
自動更新ができるかどうか試してみてください

**Comment by tanakah** [comment]
きちんと自動更新できました！
迅速な対応ありがとうございました。

**Comment by himuro-majika** [comment]
よかったです
他にも気づいた点・分からない点あればいつでもご連絡いただければと思います。
また他にもGreasy Forkで公開しているUserscriptがいくつかあるので良ければ使ってみてください
https://greasyfork.org/ja/scripts?set=2445
